// Generated by CoffeeScript 1.6.3
(function() {
  var Command, Validation;

  Validation = require('boco-validation').Validation;

  Command = (function() {
    function Command(props) {
      if (props == null) {
        props = {};
      }
      this.id = props.id;
      this.name = props.name;
      this.setParameters(props.parameters);
      this.setDefaults();
    }

    Command.prototype.setDefaults = function() {
      return this.name != null ? this.name : this.name = this.constructor.name;
    };

    Command.prototype.setParameters = function(params) {
      return this.parameters = this.constructParameters(params);
    };

    Command.prototype.constructParameters = function(params) {
      if (params == null) {
        params = {};
      }
      return params;
    };

    Command.prototype.validateParameters = function() {
      return new Validation({
        subject: this.parameters
      });
    };

    return Command;

  })();

  module.exports = Command;

}).call(this);

/*
//@ sourceMappingURL=Command.map
*/
